### ISSUE TITLE
Expert initialization data not released in test-set

### ISSUE THREAD

**Issue by hxssgaa** [anonrabit/DialFRED#10]
Hi,

We noticed that the expert initialization data is not released in the test-set which is used to initializa the previous state when performing each sub-task, I'm not sure whether this is intended because the the measure of SR in validation set assumes every previous sub-task already succeed with expert initialization. Otherwise how can we achieve similar SR in test-set with baseline?

**Comment by YuigaWada** [comment]
Hello, we are also encountering the same issue. Is there any approach available to attain a success rate of 0.30 for the test set? Thank you.

**Comment by xfgao** [comment]
Thanks for the question. For the test set, we intentionally remove the expert initialization data to prevent cheating. For the challenge, you don't need to compare with the 0.30 baseline since it is achieved by making use of the expert initialization.

**Comment by YuigaWada** [comment]
>  For the challenge, you don't need to compare with the 0.30 baseline since it is achieved by making use of the expert initialization.

Understood. Thank you.

**Comment by hxssgaa** [comment]
Noted with thanks. Close the issue now.
