### ISSUE TITLE
Unable to load "direction_augmented.pkl"

### ISSUE THREAD

**Issue by yingShen-ys** [anonrabit/DialFRED#2]
Hi,

I am trying to load the "direction_augmented.pk". 

However, I encountered `AttributeError: Can't get attribute 'def_value' on <module '__main__' (built-in)>` when loading the file using pickle. 

I am able to load the another two augmented files using pickle. Could you take a look at the data files?

Thank you!

**Comment by xfgao** [comment]
Sorry for the confusion caused. Before loading the pickle, we need to define the def_value function: 
`def def_value():
	return None`
The function is used to specify the default value of the dictionary. 
Hope this answers your question:)

**Comment by yingShen-ys** [comment]
Thank you for the clarification!
