### ISSUE TITLE
Stuck in rendering images

### ISSUE THREAD

**Issue by CKRE** [anonrabit/DialFRED#3]
Hi,

I am trying to render images, but the code is stuck.

Where the code goes wrong is 
``
event = super().step(dict(
            action='Initialize',
            gridSize=grid_size,
            cameraY=camera_y,
            renderImage=render_image,
            renderDepthImage=render_depth_image,
            renderClassImage=render_class_image,
            renderObjectImage=render_object_image,
            visibility_distance=visibility_distance,
            makeAgentsVisible=False,
        ))
``
in thor_env.py.

Could you take a look at the code?

Thank you!

**Comment by xfgao** [comment]
Sorry for the inconvenience caused. I'm not sure what's going on here since I have no problem rendering images by following the instructions in the README. May I ask which script are you running and what error message do you get?

**Comment by CKRE** [comment]
I run the script ``python -m alfred.gen.render_trajs`` following the instructions. The program can open the render window for AI2-Thor and reset to the specific scene. But when step to the 'Initialize' action, AI2-Thor only rendered 3 or 4 frames before being stuck. It seems that werkzeug.server did not receive the event returned.

**Comment by CKRE** [comment]
I run the script `python -m alfred.gen.render_trajs` following the instructions. The program can open the render window for AI2-Thor and reset to the specific scene. But when step to the 'Initialize' action, AI2-Thor only rendered 3 or 4 frames before being stuck. It seems that werkzeug.server did not receive the event returned.

In Log we found the following error:
```
SocketException: The socket has been shut down
  at System.Net.Sockets.Socket.Send (System.Byte[] buf) [0x00000] in <filename unknown>:0
  at AgentManager+<EmitFrame>c__Iterator3.MoveNext () [0x00000] in <filename unknown>:0
  at UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) [0x00000] in <filename unknown>:0
```

**Comment by xfgao** [comment]
I think the issue is caused by the version of Werkzeug. The correct version is "2.1.1". I have updated the requirement.txt.
Hope that fixes your issue.

**Comment by CKRE** [comment]
Thank you very much for your help. This problem has been solved.

**Comment by anonrabit** [comment]
Solved
