### ISSUE TITLE
Connection refused for downloading pretrained model

### ISSUE THREAD

**Issue by KzZheng** [anonrabit/DialFRED#4]
When I'm trying to download the pretrained model, an error occurs:
```
--2022-12-21 00:21:53--  http://pascal.inrialpes.fr/data2/apashevi/et_checkpoints.zip
Resolving pascal.inrialpes.fr (pascal.inrialpes.fr)... 194.199.16.17
Connecting to pascal.inrialpes.fr (pascal.inrialpes.fr)|194.199.16.17|:80... failed: Connection refused.
```
I wonder whether there is another way to get the pretrained model. Thanks!

**Comment by xfgao** [comment]
Unfortunately, this pretrained checkpoint is not owned by us. 
I have raised an issue in the ET repository. You can track the update here: [https://github.com/alexpashevich/E.T./issues/13](https://github.com/alexpashevich/E.T./issues/13)
