### ISSUE TITLE
FasterRCNN checkpoint not found

### ISSUE THREAD

**Issue by hariharan98m** [anonrabit/DialFRED#5]
Hi, this is an amazing project. I tried to replicate the setup and run some evals. 

I could not find from where to obtain fasterrcnn_model.pth . The link given in README http://pascal.inrialpes.fr/data2/apashevi/et_checkpoints.zip is broken. 

Would appreciate if you can provide any alternative.

**Comment by xfgao** [comment]
Hi, thanks for reaching out!
This checkpoint is owned by [alexpashevich](https://github.com/alexpashevich) and it seems the server that they use have some issues. You can find the link to the checkpoint here: https://github.com/alexpashevich/E.T./issues/13
