### ISSUE TITLE
the pretrained checkpoint downloading report 403 Forbidden

### ISSUE THREAD

**Issue by tongbc** [anonrabit/DialFRED#8]
wget http://pascal.inrialpes.fr/data2/apashevi/et_checkpoints.zip

-----

Forbidden
You don't have permission to access this resource.

**Comment by xfgao** [comment]
Thanks for your interest! This checkpoint is owned by [alexpashevich](https://github.com/alexpashevich) and it seems the server that they use have some issues. You can find the link to the checkpoint here: https://github.com/alexpashevich/E.T./issues/13

**Comment by tongbc** [comment]
Thanks a lot !
